package service

import (
	"bytes"
	"context"
	"encoding/csv"
	"fmt"
	"strconv"

	"hasufel.kj/internal/ledgr/domain"
	"hasufel.kj/internal/ledgr/repository"
)

// ExportService generates CSV and PDF exports from the expense ledger.
type ExportService struct {
	expenses repository.ExpenseRepository
}

// NewExportService creates an ExportService.
func NewExportService(expenses repository.ExpenseRepository) *ExportService {
	return &ExportService{expenses: expenses}
}

// CSV builds a CSV byte buffer for the given filters.
func (s *ExportService) CSV(ctx context.Context, orgID string, f domain.ExpenseFilters) ([]byte, error) {
	// Fetch all matching (no pagination for export).
	f.Page = 1
	f.PerPage = 10000
	expenses, _, err := s.expenses.List(ctx, orgID, f)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	w := csv.NewWriter(&buf)

	// Header row.
	_ = w.Write([]string{
		"date", "description", "category_id",
		"vendor_name", "vendor_gstin", "invoice_number",
		"gross_amount_paise", "base_amount_paise",
		"gst_rate", "cgst_paise", "sgst_paise", "igst_paise",
		"payment_method", "funding_source",
		"store_id", "has_invoice", "entry_type",
	})

	for _, e := range expenses {
		row := []string{
			e.Date,
			strOrEmpty(e.Description),
			e.CategoryID,
			strOrEmpty(e.VendorName),
			strOrEmpty(e.VendorGSTIN),
			strOrEmpty(e.InvoiceNumber),
			strconv.FormatInt(e.AmountPaise, 10),
			strconv.FormatInt(e.BasePaise, 10),
			string(e.GSTRate),
			strconv.FormatInt(e.CGSTPaise, 10),
			strconv.FormatInt(e.SGSTPaise, 10),
			strconv.FormatInt(e.IGSTPaise, 10),
			string(e.PaymentMethod),
			string(e.FundingSource),
			strOrEmpty(e.StoreID),
			boolStr(e.HasInvoice),
			string(e.EntryType),
		}
		_ = w.Write(row)
	}

	w.Flush()
	return buf.Bytes(), w.Error()
}

// PDF returns a minimal plain-text representation of the expense list.
// A production implementation would use a PDF library (e.g. go-pdf, wkhtmltopdf).
// This stub returns a UTF-8 text buffer that can be swapped for a real PDF renderer.
func (s *ExportService) PDF(ctx context.Context, orgID string, f domain.ExpenseFilters) ([]byte, error) {
	f.Page = 1
	f.PerPage = 10000
	expenses, _, err := s.expenses.List(ctx, orgID, f)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("Ledgr — Expense Export\n")
	buf.WriteString("=====================\n\n")
	for _, e := range expenses {
		buf.WriteString(fmt.Sprintf("%s  %-40s  %10d paise  %s\n",
			e.Date, strOrEmpty(e.Description), e.AmountPaise, string(e.EntryType)))
	}
	buf.WriteString("\n[Generated by Ledgr]\n")
	return buf.Bytes(), nil
}

func strOrEmpty(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func boolStr(b bool) string {
	if b {
		return "1"
	}
	return "0"
}
